### ISSUE TITLE
No menu entries with Symfony 4.4.32 in v1.3

### ISSUE THREAD

**Issue by olberger** [cameronmurphy/bootstrap-menu-bundle#10]
I'm trying to get menu entries in a Symfony 4.4.32 test app, but nothing is produced by ```{{ render_bootstrap_menu('mymenu') }}``` when with version 1.3.0

Switching back to v1.2.1 seems to fix the issue.

Maybe the support for Bootstrap 5 is fine, but preserving compatibility with Symfony LTS could be great too.

Thanks in advance.

**Comment by MulOnPomm** [comment]
I got it working with Symfony 5 when I added _menu_item._ before every _label_, _route_ and _url_ variable in link.html.twig  and href.html.twig.

**Comment by cameronmurphy** [comment]
This was indeed a regression, not specific to Symfony 4.4. Pushing a fix.
