### ISSUE TITLE
Is there an "active" state ?

### ISSUE THREAD

**Issue by picks44** [cameronmurphy/bootstrap-menu-bundle#12]
Hello there,

I just discovered this bundle, much more convenient and straight forward than KnpBundle, so thank you!
One question though, is there a "active" or "current" state management? 
Looks like it has not at first sight/test.

Thanks for the answer!

**Comment by picks44** [comment]
@cameronmurphy I just tested this simple solution, but it won't work for pages within a dropdown, maybe it needs to be enhanced a little bit I guess :

**/Resources/views/link.html.twig**
```
{% apply spaceless %}
  {% if menu_item.label is defined and (menu_item.route is defined or menu_item.url is defined) %}
  <li class="nav-item">
    <a class="nav-link {% if app.request.attributes.get('_route') == menu_item.route %}active{% endif %}" {% include '@BootstrapMenu/href.html.twig' with { menu_item } %}>
      {{- menu_item.label -}}
    </a>
  </li>
  {% endif %}
{% endapply %}
```

**Comment by cameronmurphy** [comment]
Hey @picks44, you're welcome 😊

Sure! I actually hadn't thought about active state cause the systems I was building only had dropdowns and not top-level links. Let me whip up a PR.

**Comment by cameronmurphy** [comment]
https://github.com/cameronmurphy/bootstrap-menu-bundle/pull/14

@picks44 Does this suit your needs?

**Comment by picks44** [comment]
Hello @cameronmurphy, nice, thanks for this fast PR, it works perfectly.

I have just tested this for dropdown management, what do you think?

**/Resources/views/dropdown.html.twig**
```
{% set data_attribute_name = 'data-bs-toggle' %}
{% set is_active = false %}
{% set routes = [] %}

{% if bootstrap_version == 4 %}
	{% set data_attribute_name = 'data-toggle' %}
{% endif %}

{% apply spaceless %}
{% for menu_item in menu_item.items %}
	{% set routes = routes|merge([menu_item.route]) %}
{% endfor %}
{% if app.request.attributes.get('_route') in routes %}
	{% set is_active = true %}
{% endif %}
<li class="nav-item dropdown">
	<a class="nav-link dropdown-toggle {% if is_active %} active{% endif %}" href="#" role="button" {{ data_attribute_name }}="dropdown" aria-haspopup="true" aria-expanded="false">
		{{- menu_item.label -}}
	</a>
	<div class="dropdown-menu">
		{% for menu_item in menu_item.items %}
			{% set menu_item = menu_item|merge({ 'index': loop.index0 }) %}
			{% include '@BootstrapMenu/dropdown_item.html.twig' with { menu_item } %}
		{% endfor %}
	</div>
</li>
{% endapply %}
```

**/Resources/views/dropdown_item.html.twig*
```
{% apply spaceless %}
{% if menu_item.is_divider %}
	{% if menu_item.index > 0 %}
		<div class="dropdown-divider"></div>
	{% endif %}

	{% if menu_item.label is defined %}
		<h6 class="dropdown-header">{{ menu_item.label }}</h6>
	{% endif %}
{% else %}
	<a class="dropdown-item {% if app.request.attributes.get('_route') == menu_item.route %}active{% endif %}" {% if app.request.attributes.get('_route') == menu_item.route %}aria-current="page"{% endif %} {% include '@BootstrapMenu/href.html.twig' with { menu_item } %}>
		{{- menu_item.label -}}
	</a>
{% endif %}
{% endapply %}
```

**Comment by picks44** [comment]
Any news there @cameronmurphy ? 😄

**Comment by cameronmurphy** [comment]
Hey @picks44 - sorry I've had a busy couple of months, just came back to this. Because dropdown active states are undocumented Bootstrap behaviour I've added some opt-in config flags for it. Have a play and let me know what you think.
