### ISSUE TITLE
Failed install leaves bundle activated

### ISSUE THREAD

**Issue by olberger** [cameronmurphy/bootstrap-menu-bundle#3]
I've experienced a failure at installation (see #2), and after that, I noticed that config/bundles.php has:
```
modified   config/bundles.php
@@ -15,4 +15,5 @@ return [
     Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
     Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
     Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
+    Camurphy\BootstrapMenuBundle\BootstrapMenuBundle::class => ['all' => true],
 ];
```
Maybe it's flex's fault ?

**Comment by cameronmurphy** [comment]
Hey @olberger, interesting. I've had a hunt around and I can't seem to find any documentation about how I could better configure my bundle to support removal upon failed install. Please raise a PR if you're able to find a solution 😊
