### ISSUE TITLE
Displaying menu only if user doesn't have a role

### ISSUE THREAD

**Issue by olberger** [cameronmurphy/bootstrap-menu-bundle#4]
Would it be possible to add a feature so as to configure the appearance of a menu if a role isn't granted to the user.

This could be handy in order to allow hiding the login menu if a user is already logged in.

I'm thinking of a syntax like role: '!IS_AUTHENTICATED_...' which would apply for unauthenticated users.

Would it make sense ?

**Comment by olberger** [comment]
An easy workaround is to duplicate the menu and handle this at twig level by including either variant based on a potentially elaborated twig "if" check on app.user.

**Comment by mchojrin** [comment]
@olberger did you ever implement this? I'm finding the same need... I used to solve it fine with knp-menu bundle but it got too outdated :(

**Comment by cameronmurphy** [comment]
Hey guys, apologies on my absence here - GitHub doesn't seem to make it easy to set up notifications for issues being created against my own repos. Thanks for using my bundle!

Thanks for your PR @mchojrin. Any chance you'd be able to add a test for the new behaviour?

**Comment by mchojrin** [comment]
@cameronmurphy I think I could... just not really soon... I'm in the middle of some personal inconveniencies.

If it's still needed in a week or two I'll do it ;)

**Comment by mchojrin** [comment]
Hi @cameronmurphy : I'm trying to put together a test but I'm not really sure how to go about it... Should I clone the bundle repo and write the test in it? How would I actually run the test?

Thanks!

**Comment by cameronmurphy** [comment]
Hey @olberger @mchojrin the feature was added as part of 1.5.0 :) Thanks for the PR @mchojrin!

**Comment by mchojrin** [comment]
Thanks for the update! And the work of course :)
