### ISSUE TITLE
Requirements prevent upgrading to Symfony 5

### ISSUE THREAD

**Issue by PaulDance** [cameronmurphy/bootstrap-menu-bundle#5]
When trying to upgrade a Symfony project, containing this bundle, to the latest version (Symfony 5), it failed on the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - camurphy/bootstrap-menu-bundle 1.0.0 requires symfony/twig-bundle ^4.3 -> satisfiable by symfony/twig-bundle[v4.4.0] but these conflict with your requirements or minimum-stability.
    - camurphy/bootstrap-menu-bundle 1.0.0 requires symfony/twig-bundle ^4.3 -> satisfiable by symfony/twig-bundle[v4.4.0] but these conflict with your requirements or minimum-stability.
    - Installation request for camurphy/bootstrap-menu-bundle ^1.0 -> satisfiable by camurphy/bootstrap-menu-bundle[1.0.0].
```

That happened, if I understand it well, because I explicitly requested the project's composer dependencies regarding Symfony to be at least version 5, but it seems that your requirements only accept version 4, which keeps me from upgrading. Maybe consider adding support for version 5 ?

**Comment by PaulDance** [comment]
Check out this [example composer.json](https://github.com/symfony/twig-bundle/blob/master/composer.json) from the official Twig bundle. As you can see, the '^' version specifier seems to restrict compatible versions of a requirement to at least the same major version, but doesn't allow getting to the next major version. They however specified for example `"symfony/config": "^4.4|^5.0"`, which for me says, *I accept version 4 at least 4.4 or version 5 at least 5.0*. Hope this helps.

**Comment by cameronmurphy** [comment]
Hey @PositivePaulo, thanks for the raising this issue. I've updated `composer.json` in v1.1 to support Symfony 5!
